#if !canImport(ObjectiveC)
import XCTest

extension SemanticVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemanticVersionTests = [
        ("testInitialisation", testInitialisation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SemanticVersionTests.__allTests__SemanticVersionTests),
    ]
}
#endif
