#if !canImport(ObjectiveC)
import XCTest

extension SemanticVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemanticVersionTests = [
        ("testAsString", testAsString),
        ("testBadlyFormed", testBadlyFormed),
        ("testComparison", testComparison),
        ("testDisplayString", testDisplayString),
        ("testInitialisation", testInitialisation),
        ("testInitialisationFromArrayLiteral", testInitialisationFromArrayLiteral),
        ("testInitialisationFromString", testInitialisationFromString),
        ("testInitialisationFromStringLiteral", testInitialisationFromStringLiteral),
        ("testInitialisationFromStrings", testInitialisationFromStrings),
        ("testWithV", testWithV),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SemanticVersionTests.__allTests__SemanticVersionTests),
    ]
}
#endif
